[package]
name = "linkux_server"
version = "0.1.0"
authors = ["José Miguel Sarasola <alosarjos@gmail.com>"]
edition = "2018"

[dependencies]
# CLI Tools
clap = "3.0.0-beta.2"

# API Rest Server
actix-web = "3"
actix-rt = "1.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"